language: node_js
node_js:
  - "8"
install:
    - npm install
script:
    - echo "npm test temporarily disabled"
deploy:
  provider: script
  script:
    - npm run clean && npm run build && npm run deploy:github
  skip_cleanup: true
  on:
    branch: master