language: node_js
node_js:
  - "8"
install:
    - npm install
before_script:
  - git clone --branch master https://github.com/ms314006/ms314006.github.io.git public
script:
    - npm run clean
    - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  repo: ms314006/ms314006.github.io
  target_branch: master