version: 2.1
orbs:
  node: circleci/node@8.16.0
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - run: npm install
      - run: npm run clean 
      - run: npm run build
workflows:
  build-deploy:
    jobs:
      - build-and-deploy