version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node@8.16.0
    steps:
      - checkout
      - run:
          name: Check Node.js version
          command: node -v
      - run:
          name: Install dependencies if needed
          command: npm install
      - run:
          name: Clean
          command: npm run clean
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy
          command: node ./deploy-github