version: 2.1
orbs:
  node: circleci/node:10.16.3
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run clean 
            - run: npm run build
workflows:
  build-deploy:
    jobs:
      - build-and-deploy