version: 2.1
orbs:
  node: circleci/node@8.16.0
jobs:
  build-and-deploy:
    steps:
      - checkout
      - run:
          name: Install dependencies if needed
          command: npm install
      - run:
          name: Clean
          command: npm run clean
      - run:
          name: Build
          command: npm run build